'use strict';

const mongoose = require('mongoose');

/**
 * UrlToAdsScan — persistent record of a Phase-7 "paste a URL, get ads" run.
 *
 * The old /studio/url-to-ad/scan endpoint returned the brand kit + 3
 * blueprint cards inline and forgot them the moment the response flushed.
 * That was fine for the drawer UX, but it meant the user couldn't:
 *   • come back tomorrow and see what we scraped
 *   • share a scan link with a teammate
 *   • track which of the 3 free ads they actually rendered
 *
 * Phase 7 turns the scan into a first-class document so the new
 * UrlToAdsPage can deep-link to `/studio/url-to-ads/:scanId` and users
 * get a reproducible "report" instead of a throwaway modal.
 *
 * Shape choices:
 *   - `brand` / `competitors` / `copy` are mongoose.Mixed so we can iterate
 *     on the scrape format without a schema migration for every new field.
 *   - `ads[]` tracks the blueprint AND the render lifecycle (jobId + asset)
 *     so the UI can show "not yet generated" vs "queued" vs "ready" per ad
 *     without a join.
 *   - `status` is the user-visible state machine; `adSetId` links to the
 *     Phase-5 ad-set job-parent when the user hits "generate all 3".
 */

const shotPlanItemSchema = new mongoose.Schema({
  index:       Number,
  role:        String,
  durationSec: Number,
  clipUrl:     { type: String, default: null },
  status:      { type: String, enum: ['pending','queued','rendering','ready','failed'], default: 'queued' },
  overlay:     { type: mongoose.Schema.Types.Mixed, default: null },
}, { _id: false });

const adEntrySchema = new mongoose.Schema({
  label:            { type: String },
  headline:         { type: String },
  hookLine:         { type: String },
  aspectRatio:      { type: String },
  vibe:             { type: String },
  category:         { type: String },
  prompt:           { type: String },
  negativePrompt:   { type: String },
  modelId:          { type: String },
  referenceImageUrl:{ type: String },
  referenceImageUrls: { type: [String], default: [] },
  status:           { type: String, enum: ['pending','queued','shots_ready','preview_ready','ready','rendering','stitching','failed'], default: 'pending' },
  jobId:            { type: String },
  assetId:          { type: String },
  assetUrl:         { type: String },
  shotJobIds:       { type: [String], default: undefined },     // ← THE CRITICAL ONE
  shotPlan:         { type: [shotPlanItemSchema], default: undefined },
  overlayPlan:      { type: [mongoose.Schema.Types.Mixed], default: undefined },
  totalDurationSec: Number,
  adSetId:          String,
  post:             { type: mongoose.Schema.Types.Mixed, default: undefined },
  thumbnailUrl:     { type: String },
  errorMessage:     { type: String },
  /**
   * When the ad was generated by the per-product flow, these fields tag
   * the variant so the UI can display a product chip + group cards by
   * product. Null for brand-level ads from the standard "Generate all 3"
   * path.
   */
  productId:        { type: String },
  productTitle:     { type: String },
  productPrice:     { type: mongoose.Schema.Types.Mixed },
  productImageUrl:  { type: String },
  /**
   * Which "kind" of generation produced this ad: 'image' (still) or
   * 'video' (lipsync / i2v). Lets the page render image and video ads
   * in distinct rows.
   */
  kind:             { type: String, enum: ['image', 'video'], default: 'image' },
  videoUrl:         { type: String },
}, { _id: false });

const urlToAdsScanSchema = new mongoose.Schema(
  {
    userId:    { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
    sessionId: { type: String, index: true },

    url:    { type: String, required: true, index: true },
    host:   { type: String },
    

    /**
     * Full brand kit payload. Kept as Mixed so we can enrich the scraper
     * (extra OG fields, logo palette, brand colors) without migrations.
     *   { name, siteName, url, host, title, description, headlines[],
     *     paragraphs[], images[], favicon, category, audience }
     */
    brand: { type: mongoose.Schema.Types.Mixed, default: {} },

    productCatalog: { type: mongoose.Schema.Types.Mixed },

    /**
     * Rich brand palette extracted from the primary hero image (see
     * services/scraper/brandPalette.js). Shape:
     *   { primary, accent, background, swatches: [{hex, role, brightness, saturation, coverage, source}], cssVariables }
     */
    brandPalette: { type: mongoose.Schema.Types.Mixed, default: null },

    /** Font-family stack inferred from the page CSS. */
    fonts: { type: [String], default: [] },

    /**
     * AI + heuristic business profile for polymorphic UI + prompts.
     * See services/businessProfileInference.js for shape (type, businessAssets, adStrategy, …).
     */
    businessProfile: { type: mongoose.Schema.Types.Mixed, default: null },

    /**
     * Anthropic-researched competitors. Each:
     *   { name, url, tagline, why, differentiator }
     * (Legacy seeded fields `logoUrl` / `category` / `region` are allowed
     *  via Mixed for backward compatibility with older scans.)
     */
    competitors: [{ type: mongoose.Schema.Types.Mixed }],

    /**
     * Generated ad copy pack:
     *   { headlines[], captions[], ctas[], hashtags[], openingLines[] }
     */
    copy: { type: mongoose.Schema.Types.Mixed, default: {} },

    /**
     * Full Anthropic research payload — single source of truth for the
     * URL-to-Ads page. Cached here so a re-open doesn't re-call Claude.
     *   { brand, targetAudience, competitors, competitorAds, hooks,
     *     _source, _model, _at }
     */
    research:      { type: mongoose.Schema.Types.Mixed, default: null },
    competitorAds: [{ type: mongoose.Schema.Types.Mixed }],
    audience:      { type: mongoose.Schema.Types.Mixed, default: null },

    /**
     * Competitor Intelligence Engine output (Layer 1–5 pipeline).
     *   brandIdentity     — resolved handles / markets / confidence
     *   battlefieldReport — counter-strategy + hero insights for the UI
     *   collection        — per-source health report
     *   brandId           — FK into the deduplicated Brand collection
     *
     * This field is populated best-effort — a scan can still succeed if the
     * intelligence run fails or the orchestrator is not configured. The UI
     * should gracefully no-op when this is null.
     */
    intelligence: { type: mongoose.Schema.Types.Mixed, default: null },

    /** Apify-backed competitive + crawl payloads (filled by url-to-ads enrich worker).
     *  competitorAds shape (post-AI rewrite): array of per-competitor result
     *  objects, each `{ competitor, competitorUrl, ads: [...with intelligence],
     *  strategiesAttempted, successfulStrategy, error, errorReason, fetchedAt }`.
     *  competitorAdsSummary holds the AI-derived dashboard-headline payload:
     *  totals, winners, topPatterns, spendingHeavyweights, errors. */
    apifyData: {
      competitorAds:        [{ type: mongoose.Schema.Types.Mixed }],
      competitorAdsSummary: { type: mongoose.Schema.Types.Mixed, default: null },
      instagramProfiles:    [{ type: mongoose.Schema.Types.Mixed }],
      instagramTopPosts:    [{ type: mongoose.Schema.Types.Mixed }],
      tiktokProfiles:       [{ type: mongoose.Schema.Types.Mixed }],
      googleMapsPlaces:     [{ type: mongoose.Schema.Types.Mixed }],
      lastRefreshedAt:      { type: Date, default: null },
      _raw:                 { type: mongoose.Schema.Types.Mixed, default: null },
    },

    studioCreatives: [{
      adSetId: String,
      modelId: String,
      kind: { type: String, enum: ['image', 'video'] },
      durationSec: Number,
      aspectRatio: String,
      isComboVideo: Boolean,
      createdAt: { type: Date, default: Date.now },
    }],

    /**
     * Money math — AI-calibrated CPL/LTV/conversion benchmarks per scan
     * (see services/moneyMath.js). Stored as Mixed because the AI pipeline
     * keeps adding new fields (verticalReasoning, calibrationNotes,
     * modelingAssumptions, confidenceLevel, warnings, source, …) and we
     * don't want a schema migration each time.
     *   { vertical, verticalReasoning, benchmarks, projections,
     *     calibrationNotes[], modelingAssumptions, confidenceLevel,
     *     warnings[], source, generatedAt }
     */
    moneyMath: { type: mongoose.Schema.Types.Mixed, default: null },

    /**
     * Roast — AI-generated brutal-truth insights surfaced as the headline
     * panel of the report (see services/roastEngine.js). Shape:
     *   { insights: [{ severity, category, headline, body, metrics[],
     *                  estimatedCost, fixPrompt, fixLabel }],
     *     source: 'ai' | 'cache' | 'fallback',
     *     generatedAt }
     */
    roast: { type: mongoose.Schema.Types.Mixed, default: null },

    /**
     * Pattern-engine “what competitors skip” summary (see
     * services/urlToAds/competitiveGapAnalysis.js). Filled after Apify Meta
     * ads land. Null when insufficient samples.
     */
    competitiveGap: { type: mongoose.Schema.Types.Mixed, default: null },

    /**
     * WhatsApp-commerce signals — Gulf-region differentiator. Detected at
     * scan time by services/scraper/detectWhatsAppCommerce.js. Mixed so we
     * can iterate on what we surface without a migration. Shape:
     *   { detected: boolean,
     *     waLinks:  string[],         // wa.me / api.whatsapp.com / chat.whatsapp.com URLs
     *     waNumbers: string[],        // E.164 phone numbers found near WA
     *     waCtas:   string[],         // detected CTA strings ("DM for prices", etc.)
     *     cataloguePresence: boolean, // wa.me /c/ or "catalog" near WA
     *     confidence: 'low' | 'medium' | 'high' }
     */
    whatsappCommerce: {
      type: mongoose.Schema.Types.Mixed,
      default: () => ({
        detected: false,
        waLinks: [],
        waNumbers: [],
        waCtas: [],
        cataloguePresence: false,
        confidence: 'low',
      }),
    },

    /**
     * Deterministic 5-variant copy pack tuned for WA-first shoppers.
     * Populated only when whatsappCommerce.detected === true. See
     * services/urlToAds/whatsappCopyVariants.js for the contract:
     *   [{ id, label, headline, body, cta }, ...]
     */
    whatsappCopyPack: { type: mongoose.Schema.Types.Mixed, default: null },

    metaDeploy: {
      campaignId:  { type: String, default: null },
      status: {
        type: String,
        enum: ['not_deployed', 'deployed', 'paused', 'failed'],
        default: 'not_deployed',
      },
      deployedAt:  { type: Date, default: null },
      spendToDate:   { type: Number, default: null },
      metrics:       { type: mongoose.Schema.Types.Mixed, default: null },
    },

    digestEnrolled:   { type: Boolean, default: false },
    digestLastSentAt: { type: Date, default: null },

    /**
     * 3 free ad blueprints with render lifecycle per card.
     */
    // ads: [adEntrySchema],
    ads: { type: [mongoose.Schema.Types.Mixed], default: [] },
    adSpecs: { type: [mongoose.Schema.Types.Mixed], default: [] },
    /** Phase-5 ad-set parent id, populated after the user hits "Generate all". */
    adSetId: { type: String, default: null },

    status: {
      type: String,
      enum: ['queued','scanning', 'ready', 'rendering', 'partial', 'failed', 'archived'],
      default: 'scanning',
      index: true,
    },

    errorMessage: { type: String },

    /** Free trial accounting — the first scan per session is free even if
     *  the user's balance is 0, so the investor demo Just Works. */
    freeTrialConsumed: { type: Boolean, default: false },


    confirmedBrand: {
      confirmed:   { type: Boolean, default: false },
      confirmedAt: { type: Date },
 
      // Editable copies of the scraped fields. Null until the gate is opened;
      // the UI seeds them from the raw scan, the user corrects, we persist.
      name:        { type: String },
      category:    { type: String },
 
      // Final palette the user kept — array of hex strings, max ~6.
      palette:     [{ type: String }],
 
      // Confirmed social handles. Each platform: { handle, url, confirmed }.
      socials: {
        instagram: { type: mongoose.Schema.Types.Mixed, default: null },
        facebook:  { type: mongoose.Schema.Types.Mixed, default: null },
        tiktok:    { type: mongoose.Schema.Types.Mixed, default: null },
        linkedin:  { type: mongoose.Schema.Types.Mixed, default: null },
        twitter:   { type: mongoose.Schema.Types.Mixed, default: null },
      },
 
      // Competitor list after the user removed wrong/own entries and/or added
      // their own. Mixed so it matches the existing competitor shape.
      competitors: [{ type: mongoose.Schema.Types.Mixed }],
 
      // Audit: which fields the user actually changed (for product analytics —
      // tells you which extractor is least trusted and needs work).
      edits: { type: mongoose.Schema.Types.Mixed, default: {} },
    },
  },
  
  { timestamps: true }
);

// Helpful compound indices — the two queries we care about:
//   list scans for this user ordered by freshness
//   de-dupe by (owner, url) so a double-click doesn't spam records
urlToAdsScanSchema.index({ userId: 1, createdAt: -1 });
urlToAdsScanSchema.index({ sessionId: 1, createdAt: -1 });
urlToAdsScanSchema.index({ userId: 1, url: 1 });

module.exports = mongoose.model('UrlToAdsScan', urlToAdsScanSchema);
